language: node_js

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

node_js:
  - '0.10'

before_script:
  - 'npm install -g bower grunt-cli'

after_script: "npm install coveralls@2.10.0 && cat ./test/coverage/*/lcov.info | coveralls"